[tool.poetry]
name = "sample"
version = "0.2.0"
description = "Sample Python application"
authors = ["D Creemer <@dcreemer>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
coverage = {extras = ["toml"], version = "^5.5"}
flake8 = "^3.9"
flake8-bandit = "^2.1"
flake8-isort = "^4.0.0"
isort = "^5.9"
mypy = "^0.910"
pyproject-flake8 = "^0.0.1-alpha.2"
pytest = "^6"
pytest-cov = "^2.12"
safety = "^1.10"

[tool.poetry.scripts]
sample = "main:main"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=sample --cov-report html --cov-report term"

[tool.flake8]
max-line-length = "105"
# (S101 don't warn about using asserts in test code)
# (E501 don't warn about ling length)
per-file-ignores = "tests/*:E501,S101 */*/tests/*:E501,S101"

[tool.black]
line-length = 105
target-version = ["py310"]

[tool.coverage.run]
branch = true
parallel = true
source = ["src"]

[tool.mypy]
python_version = "3.10"
mypy_path = "$MYPY_CONFIG_FILE_DIR/typings"
strict = true
warn_return_any = true
warn_unreachable = true
warn_no_return = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
