[tool.poetry]
name = "sample"
version = "0.2.0"
description = "Sample Python application"
authors = ["D Creemer <@dcreemer>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.1"
coverage = {extras = ["toml"], version = "^6.3"}
flake8 = "^5"
flake8-bandit = "^4"
flake8-isort = "^4"
isort = "^5"
mypy = "^0.971"
pyproject-flake8 = "^5"
pytest = "^7"
pytest-cov = "^3"
safety = "^2"
flake8-black = "^0.3"

[tool.poetry.scripts]
sample = "main:main"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=sample --cov-report html --cov-report term"

[tool.flake8]
max-line-length = "105"
# ignore whitespace before ":" -- compatible with black
extend-ignore = "E203"
# (S101 don't warn about using asserts in test code)
# (E501 don't warn about line length)
per-file-ignores = "tests/*:E501,S101 */*/tests/*:E501,S101"

[tool.black]
line-length = 105
target-version = ["py310"]
preview = true

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true
parallel = true
source = ["src"]

[tool.mypy]
python_version = "3.10"
mypy_path = "$MYPY_CONFIG_FILE_DIR/typings"
strict = true
warn_return_any = true
warn_unreachable = true
warn_no_return = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
